name: Trigger on Successful Check for Main Branch

on:
  workflow_dispatch:
  check_run:
    types: 
      - completed
    

jobs:
  handle-success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Successful Check Action
        run: echo "The check '${{ github.event.check_run.name }}' on the main branch has completed successfully!"
