name: Dispatch Workflow

on:
  workflow_dispatch:

jobs:
  dispatch_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main  

    - name: Get latest commit hash
      id: get_commit
      run: |
        gitHash=$(git rev-parse HEAD | cut -c1-7)
        echo $gitHash
        echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Get latest commit message
      id: get_message
      run: |
        gitMesage=$(git log -1 --pretty=%B | sed -n '1p' | tr ' ' '-')
        echo $gitMesage
        echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
