name: Build and/or Deploy Imaginary Containers Hydra server

on:
    workflow_dispatch:
      inputs:
        job_choice:
          description: 'Choose which job(s) to run'
          required: true
          default: 'deploy'
          type: choice
          options:
            - deploy
            - build
            - build_deploy
        variable:
          description: 'Input image tag to use'
          required: true
          default: 'latest'

jobs:
  build:
    if: ${{ github.event.inputs.job_choice == 'build' || github.event.inputs.job_choice == 'build_deploy' }}
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
      
      - name: Clone external repository and replace Dockerfile
        run: |
          git clone https://github.com/h2non/imaginary.git
          cd imaginary
          mv ../.github/build/imaginary/Dockerfile ./Dockerfile

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1'
        
      - name: Go mod tidy
        run: |
          cd imaginary
          go mod tidy

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        
      - name: Build 
        run: |
          pwd
          ls -la
          cd imaginary
          docker build -t truefunnny/go-test:latest .
          docker push truefunnny/go-test:${{ github.event.inputs.variable }}

  deploy:
    if: ${{ github.event.inputs.job_choice == 'deploy' || github.event.inputs.job_choice == 'build_deploy' }}
    runs-on: ubuntu-latest    
    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
       

    - name: Pull new version of container on services server
      run: |
          docker pull truefunnny/go-test:${{ github.event.inputs.variable }}

    - name: Deploy new version of container
      run: |
        docker run -d --restart=always -p 9000:9000 --name imaginary truefunnny/go-test:${{ github.event.inputs.variable }} -enable-url-source

