name: Build imaginary
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        run: |
          git clone https://github.com/h2non/imaginary.git
      - name: Checkout your repo for Dockerfile
        uses: actions/checkout@v3
        with:
          # Використовуємо поточний репозиторій для Dockerfile
          path: ./Dockerfile

      
          

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
        
      - name: Versions
        run: go version

      - name: Add depp
        run: |
          cp Dockerfile ../imaginary/Dockerfile
          pwd
          ls -la
          cd ../imaginary
          ls -la
          go mod tidy

      - name: Build 
        run: |
          pwd
          ls -la
          cd imaginary
          docker build -t test:1 .

      
  
