name: Build container doc-serve and deploy to Stage
on:
    workflow_dispatch:
    workflow_call:
    push:
      branches:
        - main
      paths: 
       - 'api/**'
       - 'cmd/doc-seve/**'
#        - docker-doc-server
#      paths-ignore:
#        - '.github/workflows/**'

#concurrency:
#      group: ${{ github.head_ref || github.ref }}


jobs:

  build-doc-container:
    runs-on: ubuntu-latest
    steps:

    - name: Test
      run: |
        echo "test"
