name: escape
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Escape commit message for JSON
        id: escaped_commit_message
        run: echo "message=$(jq -Rs . <<< '${{ github.event.head_commit.message }}')" >> "$GITHUB_ENV"
        
      - name: Use escaped commit message
        run: echo "Escaped message: ${{ env.message }}"
          

        

     

