name: Build and deploy AI bot to DEV server
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: promova_backend_1
    outputs:
      ecr_pass: ${{ steps.ecr_password.outputs.ecr_pass }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
     

