name: Check if last commit was a merge from Dev
on:
  push:
    branches:
      - main

jobs:
  detect-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if last commit was a merge from Dev
        run: |
          git fetch origin Dev --depth=1
          if git log --merges -n 1 --format=%P | grep "$(git rev-parse origin/Dev)"; then
            echo "Detected merge from Dev to Main"
            exit 0
          else
            echo "No recent merge from Dev"
            exit 1
          fi
        

     

