name: Push to All Branches

on:
  push:
    branches:
      - '**'  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     

      - name: Run step only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This step runs only on the main branch"

      - name: Upload reports to S3
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        run: |
          echo "second step"
