name: Check Main Push Type

on:
  push:
    branches:
      - main

jobs:
  check-push-type:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Важливо отримати повну історію для аналізу
      
      - name: Determine push type
        id: check-type
        run: |
          # Отримуємо хеш останнього коміту
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Current commit: $CURRENT_COMMIT"
          
          # Перевіряємо, чи є останній коміт мердж-комітом
          IS_MERGE=$(git show --no-patch --format="%p" $CURRENT_COMMIT | wc -w)
          
          if [ "$IS_MERGE" -gt 1 ]; then
            echo "This is a merge commit with multiple parents"
            
            # Отримуємо батьківські коміти
            PARENTS=$(git show --no-patch --format="%p" $CURRENT_COMMIT)
            echo "Parent commits: $PARENTS"
            
            # Перевіряємо, чи один з батьків належить до dev гілки
            DEV_BRANCH_CONTAINS=""
            for PARENT in $PARENTS; do
              if git branch --contains $PARENT | grep -q "dev"; then
                DEV_BRANCH_CONTAINS="true"
                echo "Found parent commit $PARENT that belongs to dev branch"
                break
              fi
            done
            
            if [ -n "$DEV_BRANCH_CONTAINS" ]; then
              echo "This is a merge from dev branch to main"
              echo "push_type=merge_from_dev" >> $GITHUB_OUTPUT
            else
              echo "This is a merge, but not from dev branch"
              echo "push_type=other_merge" >> $GITHUB_OUTPUT
            fi
          else
            echo "This is a direct commit to main (not a merge)"
            echo "push_type=direct_commit" >> $GITHUB_OUTPUT
          fi
      
      - name: Take action based on push type
        run: |
          if [ "${{ steps.check-type.outputs.push_type }}" == "direct_commit" ]; then
            echo "Warning: Direct commit to main detected!"
            # Тут можна додати додаткові дії для прямого коміту в main
            # Наприклад, відправити сповіщення або згенерувати помилку
            
          elif [ "${{ steps.check-type.outputs.push_type }}" == "merge_from_dev" ]; then
            echo "OK: This is a proper merge from dev branch"
            # Можна додати додаткові перевірки для мерджу з dev
            
          else
            echo "Warning: Merge detected, but not from dev branch"
            # Тут можна додати обробку для інших видів мерджу
          fi
