name: Retry

on:
  workflow_dispatch: 

jobs:
  autotests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Retry command with timeout
        uses: nick-invision/retry@v2 # Правильне ім'я бібліотеки
        with:
          max_attempts: 3
          timeout_seconds: 5
          retry_on: error
          command: |
            echo 'some command that could potentially fail'
            docker build -t test:1 .
            