name: Retry

on:
  workflow_dispatch: 
  
jobs:
  autotests:
    runs-on: ubuntu-latest
    steps:
      - name: Use the reusable workflow
        run: |
	  for i in {1..3}; do
   	    echo: Attempt $1
            docker build -t test:1 .
  	  done
				  
