name: Retry

on:
  workflow_dispatch: 
  
jobs:
  autotests:
    runs-on: ubuntu-latest
    steps:
      - name: Use the reusable workflow
			  uses: nick-fields/retry@v2
			  with:
				  max_attempts: 3
				  retry_on: error
				  timeout_seconds: 5
				  command: |
					echo 'some command that would potentially fail'	