name: Retry

on:
  workflow_dispatch: 

concurrency:
      group: ${{ github.head_ref || github.ref }}

jobs:
  autotests:
    runs-on: ubuntu-latest
    steps:
      - name: Use the reusable workflow
			  # Use the retry action
			  uses: nick-fields/retry@v2
			  with:
				  max_attempts: 5
				  retry_on: error
				  timeout_seconds: 5
				command: |
				  docker build -t test:1 .
