name: Sync Main branch to Dev

on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
  
jobs:
  sync_dev_uat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Merge main into dev
      run: |
        # Переключитися на dev (або створити, якщо немає)
        git checkout dev || git checkout -b dev origin/dev

        # Мердж з main
        git merge origin/main --no-edit

        # Коміт з прапором skip-ci
        git commit --amend -m "Sync main → dev [skip-ci]" || echo "No amend needed"

        # Push змін
        git push origin dev
