
name: test-and-lint
on:
  workflow_call:
  push:
jobs:
  test:
    # runner temporary down
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Test trigger
        if: ${{ github.event_name != 'push' }}
        run: |
          echo "test----------------"
