
name: Build
on:
  push:
jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Notify
        run: |
          echo $branch_name

      - name: Notify on Failure
        if: ${{ failure() && (env.branch_name == 'main' || env.branch_name == 'stage') }}
        run: |
          echo " test--------"
